name: deudores_app
description: "Sistema de control de cuentas PWA"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- PAQUETES PRINCIPALES ---
  
  # Base de datos y Autenticación
  supabase_flutter: ^2.10.3
  
  # Gestión de Estado (Para la Tasa BCV y Carrito)
  provider: ^6.1.1
  
  # Peticiones Web (Para consultar la API del BCV)
  http: ^1.2.0
  
  # Para abrir WhatsApp y enlaces externos
  url_launcher: ^6.2.5
  
  # Iconos de Material Design
  cupertino_icons: ^1.0.6

  # Utilidades
  uuid: ^4.0.0 # Generador de IDs únicos
  intl: ^0.19.0 # Formateo de fechas

  pdf: ^3.10.4
  printing: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# --- CONFIGURACIÓN DE FLUTTER ---
flutter:
  uses-material-design: true

  # Aquí es donde se registran las imágenes
  assets:
    - lib/assets/logo.jpg
    - lib/assets/logo2.PNG